// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttdoaszcxhwkxlchogeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0ZG9hc3pjeGh3a3hsY2hvZ2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMjQxNzAsImV4cCI6MjA3NjcwMDE3MH0.IOBLx8pbYl9Ri0OWldTgAQ26jVjKrJ6D-jNfPeAJUXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});